---
- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_net_name }}"
    address_prefixes: "{{ vm_net_address_prefix }}"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_net_subnet_name }}"
    address_prefix: "{{ vm_net_subnet_address_prefix }}"
    virtual_network: "{{ vm_net_name }}"

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: Static
    name: "{{ vm_net_public_ip_name }}"
    domain_name_label: "{{ vm_net_public_ip_dns_label }}"
  register: output_ip_address

- name: Output public IP
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}"

- name: Create Network Security Group
  azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_net_security_group_name }}"
    rules:
      - name: 'allow_rdp'
        protocol: Tcp
        destination_port_range: 3389
        access: Allow
        priority: 1001
        direction: Inbound
      
      - name: 'allow_web_traffic'
        protocol: Tcp
        destination_port_range:
          - 80
          - 443
        access: Allow
        priority: 1002
        direction: Inbound
      
      - name: 'allow_powershell_remoting'
        protocol: Tcp
        destination_port_range:
          - 5985
          - 5986
        access: Allow
        priority: 1003
        direction: Inbound

- name: Create a network interface
  azure_rm_networkinterface:
    name: "{{ vm_net_interface_name }}"
    resource_group: "{{ resource_group }}"
    virtual_network: "{{ vm_net_name }}"
    subnet_name: "{{ vm_net_subnet_name }}"
    security_group: "{{ vm_net_security_group_name }}"
    ip_configurations:
      - name: default
        public_ip_address_name: "{{ vm_net_public_ip_name }}"
        primary: True